apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ingress-nginx

resources:
- https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml
- kind-ingress-nginx-configmap-tcp-services.yaml

patches:
- path: kind-ingress-nginx-deployment.patch.yaml
- path: kind-ingress-nginx-service.patch.yaml

